//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VidUSB2.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_VIDUSB2_FORM                101
#define IDC_HAND1                       106
#define IDR_MAINFRAME                   128
#define IDR_VIDUSBTYPE                  129
#define IDD_DIALOG_FEATURECONTROL       133
#define IDB_BITMAP_ICON                 136
#define IDD_DIALOG_RECONNECTION         138
#define IDD_DIALOG_PROGRESS             139
#define IDD_DIALOG_PRODUCTION           140
#define IDB_BITMAP_BTN                  143
#define IDD_DIALOG_OPTIONS              144
#define IDD_DIALOG_ALTSETTING           145
#define IDD_DIALOG_SELECTDEV            148
#define IDC_COMBO_OB                    1001
#define IDC_SCROLLBAR_ADDRESS           1002
#define IDC_PROGRESS_DIFMEAN            1002
#define IDC_PROP_EDIT_ID                1003
#define IDC_SLIDER_THRESHOD             1003
#define IDC_PROP_EDIT_SET               1004
#define IDC_STATIC_THOD                 1004
#define IDC_PROP_GET                    1005
#define IDC_CHECK_BLC                   1005
#define IDC_PROP_SET                    1006
#define IDC_I2C_SET                     1007
#define IDC_BUTTON_RESET                1007
#define IDC_I2C_GET                     1008
#define IDC_I2C_EDIT_INDEX              1009
#define IDC_SCROLLBAR_EDGEENHANCE       1009
#define IDC_I2C_EDIT_SET                1010
#define IDC_PROP_EDIT_GET               1011
#define IDC_I2C_EDIT_GET                1012
#define IDC_CHECK_GAIN                  1012
#define IDC_PROP_ID                     1013
#define IDC_PROP_VALUE_SET              1014
#define IDC_PROP_VALUE_GET              1015
#define IDC_SCROLLBAR_GAIN              1015
#define IDC_SCROLLBAR_GAIN_B            1015
#define IDC_I2C_INDEX                   1016
#define IDC_SCROLLBAR_RGAIN             1016
#define IDC_I2C_VALUE_SET               1017
#define IDC_SCROLLBAR_BGAIN             1017
#define IDC_I2C_VALUE_GET               1018
#define IDC_SCROLLBAR_BLCWEIGH          1018
#define IDC_GPIO_VALUE_SET              1019
#define IDC_GPIO_EDIT_SET               1020
#define IDC_GPIO_GET                    1021
#define IDC_I2C_SELECT_DEVICE           1022
#define IDC_I2C_EDIT_SET5               1023
#define IDC_PROP_EDIT_DADDRESS          1024
#define IDC_DISP_PROP_PAGES             1025
#define IDC_I2C_BASE                    1026
#define IDC_EDIT_EDGE                   1026
#define IDC_I2C_EDIT_BASE               1027
#define IDC_GPIO_SET                    1028
#define IDC_EDIT_GAIN                   1028
#define IDC_GPIO_VALUE_GET              1029
#define IDC_GPIO_EDIT_GET               1030
#define IDC_MACROVISION                 1031
#define IDC_EDIT_BLCWEIGH               1031
#define IDC_I2C_EDIT_R                  1032
#define IDC_SNAPSHOT                    1033
#define IDC_EDIT_RGAIN                  1033
#define IDC_I2C_EDIT_W                  1034
#define IDC_EDIT_BGAIN                  1034
#define IDC_I2C_EDIT_I                  1035
#define IDC_PROP_EDIT_DVALUE            1036
#define IDC_SCROLLBAR_VALUE             1037
#define IDC_I2C_BYTES_TEXT              1038
#define IDC_I2C_VALUE_TEXT              1039
#define IDC_BUTTON_FUNCTION             1040
#define IDC_PROP_EDIT_FADDRESS          1041
#define IDC_PROP_EDIT_FVALUE            1042
#define IDC_BUTTON_FUNCTIONREAD         1043
#define IDC_CHECK_MIRROR                1044
#define IDC_COMBO_WBM                   1046
#define IDC_STATIC_GAINGROUP            1050
#define IDC_STATIC_EDGEGROUP            1051
#define IDC_STATIC_BLCGROUP             1052
#define IDC_PROGRESS1                   1053
#define IDC_STATIC_LOADFEATURES         1054
#define IDC_SLIDER_GAIN                 1056
#define IDC_SLIDER_EDGE                 1057
#define IDC_STATIC_SINGLEREGISTER       1057
#define IDC_SLIDER_BLC                  1058
#define IDC_STATIC_USBEEPROM            1058
#define IDC_SLIDER_REDGAIN              1059
#define IDC_STATIC_CAMERAEEPROM         1059
#define IDC_SLIDER_BGAIN                1060
#define IDC_STATIC_SLECT                1060
#define IDC_BUTTON_USBRFILE             1061
#define IDC_BUTTON_USBWFILE             1062
#define IDC_COMBO_OBJ                   1063
#define IDC_EDIT_ADDRESS                1064
#define IDC_SCROLLBAR_ADD               1065
#define IDC_EDIT_DATA                   1066
#define IDC_SCROLLBAR_DATA              1067
#define IDC_BUTTON_CAMWFILE             1068
#define IDC_BUTTON_CAMWDSPEEPROM        1068
#define IDC_STATIC_ADDRESS              1069
#define IDC_STATIC_VALUE                1070
#define IDC_CHECK_INTERLEAVE            1071
#define IDC_BUTTON_CAMWDSP              1072
#define IDC_CHECK_STATUSBIT             1073
#define IDC_STATIC_COMMSETTING          1074
#define IDC_EDIT_DELAY                  1075
#define IDC_STATIC_DELAY                1076
#define IDC_BUTTON_SENDTOCAM            1077
#define IDC_STATIC_VERSION              1078
#define IDC_STATIC_COMMSETTING2         1078
#define IDC_STATIC_COMPANY              1079
#define IDC_CHECK_BLCOSD                1081
#define IDC_STATIC_BLCWEIGHT            1082
#define IDC_BUTTON_CAMINFO              1083
#define IDC_EDIT_CAMINFO                1084
#define IDC_STATIC_BLCPOSY              1085
#define IDC_RADIO_BOB                   1086
#define IDC_RADIO_WEAVE                 1087
#define IDC_RADIO_CRT                   1088
#define IDC_RADIO_LCD                   1089
#define AFX_ID_OPTIONS_ENHANCEDMOTION   1090
#define IDC_COMBO_SHUTTER               1091
#define AFX_ID_OPTIONS_OPTIMIZATION     1091
#define IDC_RADIO_BETTER_QUALITY        1092
#define IDC_COMBO_BLCSIZE               1093
#define IDC_RADIO_LESS_CPU_USAGE        1093
#define IDC_RADIO_EMS_AUTO              1094
#define IDC_CHECK_EDGE                  1095
#define IDC_BUTTON1                     1096
#define IDC_COMBO_BLCPOS                1098
#define IDC_COMBO_BLCPOS_Y              1099
#define IDC_STATIC_WBM_ELM              1117
#define IDC_STATIC_RGAIN                1119
#define IDC_STATIC_BGAIN                1120
#define IDC_STATIC_WBMODE               1129
#define IDC_STATIC_SHUTTER              1132
#define IDC_STATIC_BLCSIZE              1133
#define IDC_STATIC_WINPOS               1134
#define IDC_RADIO_ALTSET0               1135
#define IDC_RADIO_ALTSET1               1136
#define IDC_STATIC_PLUGIN               1137
#define IDC_STATIC_DRIVER               1138
#define IDC_BTN_SWITCH                  1139
#define IDC_BTN_EXIT                    1140
#define ID_TIMER1                       2000
#define ID_TIMER2                       2001
#define ID_TIMER3                       2002
#define ID_TIMER4                       2003
#define ID_TIMER5                       2004
#define ID_TIMER6                       2005
#define ID_TIMER7                       2006
#define ID_OPTIONS_VIDEOCAPTUREFILTER   32771
#define ID_OPTIONS_VIDEOCAPTUREPIN      32772
#define ID_FILE_SETSNAPIMAGEFOLDER      32773
#define ID_CAPTURE_SNAP                 32774
#define ID_FILE_SETCAPTUREIMAGEFOLDER   32775
#define ID_CAPTURE_VIDEOCAPTURE         32776
#define ID_CAPTURE_STOPVIDEOCATPURE     32777
#define ID_CAMERACONTROL_CAMERACONTROL  32778
#define ID_CONTROL_PRODUCTIONTOOL       32784
#define ID_HELP_HELP                    32785
#define ID_OPTIONS_OPTIONS              32788
#define ID_OPTIONS_ENHANCEDMOTIONSTABILIZATION 32789
#define ID_OPTIONS_ADVANCED             32790
#define ID_OPTIONS_RESTART              32791
#define ID_OPTIONS_FACTORY              32792
#define ID_FILE_ENABLESNAPSHOTS         32793
#define ID_OPTIONS_NORMAL               32794
#define ID_OPTIONS_90DEGREES            32795
#define ID_OPTIONS_180DEGREES           32796
#define ID_OPTIONS_270DEGREES           32797
#define ID_OPTIONS_FLIP                 32798
#define ID_OPTIONS_MIRROR               32799
#define ID_FILE_SNAP_BMP                32800
#define ID_FILE_SNAP_GIF                32801
#define ID_FILE_SNAP_JPEG               32802
#define ID_FILE_SNAP_PNG                32803
#define ID_PIXCORR_AUTO                 32804
#define ID_PIXCORR_CLEAR                32805
#define ID_PIXCORR_REMOVE               32806
#define ID_CAMEARA_SLECTING             32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
